<?xml version="1.0" encoding="utf-8"?><Database Name="Database" Class="LinqToDbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\Database.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Assignments" Member="Assignments">
    <Type Name="Assignment">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PostId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClassId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Path" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="User_Assignment" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="Post_Assignment" Member="Post" ThisKey="PostId" OtherKey="Id" Type="Post" IsForeignKey="true" />
      <Association Name="UserClass_Assignment" Member="UserClass" ThisKey="ClassId" OtherKey="Id" Type="UserClass" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Books" Member="Books">
    <Type Name="Book">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Size" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Path" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="User_Book" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="User_Assignment" Member="Assignments" ThisKey="Id" OtherKey="UserId" Type="Assignment" />
      <Association Name="User_Book" Member="Books" ThisKey="Id" OtherKey="UserId" Type="Book" />
      <Association Name="User_Post" Member="Posts" ThisKey="Id" OtherKey="UserID" Type="Post" />
      <Association Name="User_Comment" Member="Comments" ThisKey="Id" OtherKey="UserId" Type="Comment" />
      <Association Name="User_Enrollment" Member="Enrollments" ThisKey="Id" OtherKey="UserId" Type="Enrollment" />
      <Association Name="User_UserClass" Member="UserClasses" ThisKey="Id" OtherKey="InstructorId" Type="UserClass" />
      <Association Name="User_PostSubmission" Member="PostSubmissions" ThisKey="Id" OtherKey="UserID" Type="PostSubmission" />
    </Type>
  </Table>
  <Table Name="dbo.Posts" Member="Posts">
    <Type Name="Post">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ClassId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Summary" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Details" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserRole" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Submission" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Tag" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Post_Assignment" Member="Assignments" ThisKey="Id" OtherKey="PostId" Type="Assignment" />
      <Association Name="Post_Comment" Member="Comments" ThisKey="Id" OtherKey="PostId" Type="Comment" />
      <Association Name="Post_PostSubmission" Member="PostSubmissions" ThisKey="Id" OtherKey="PostId" Type="PostSubmission" />
      <Association Name="User_Post" Member="User" ThisKey="UserID" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="UserClass_Post" Member="UserClass" ThisKey="ClassId" OtherKey="Id" Type="UserClass" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Comments" Member="Comments">
    <Type Name="Comment">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ClassId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PostId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Data" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserRole" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="Post_Comment" Member="Post" ThisKey="PostId" OtherKey="Id" Type="Post" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="User_Comment" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="UserClass_Comment" Member="UserClass" ThisKey="ClassId" OtherKey="Id" Type="UserClass" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Enrollment" Member="Enrollments">
    <Type Name="Enrollment">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ClassId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Role" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Notifications" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="User_Enrollment" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="UserClass_Enrollment" Member="UserClass" ThisKey="ClassId" OtherKey="Id" Type="UserClass" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserClasses" Member="UserClasses">
    <Type Name="UserClass">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InstructorId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StudentsEnrolled" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InstructorName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Role" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Institute" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Notifications" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="UserClass_Assignment" Member="Assignments" ThisKey="Id" OtherKey="ClassId" Type="Assignment" />
      <Association Name="UserClass_Post" Member="Posts" ThisKey="Id" OtherKey="ClassId" Type="Post" />
      <Association Name="UserClass_Comment" Member="Comments" ThisKey="Id" OtherKey="ClassId" Type="Comment" />
      <Association Name="UserClass_Enrollment" Member="Enrollments" ThisKey="Id" OtherKey="ClassId" Type="Enrollment" />
      <Association Name="UserClass_Resource" Member="Resources" ThisKey="Id" OtherKey="ClassId" Type="Resource" />
      <Association Name="User_UserClass" Member="User" ThisKey="InstructorId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PostSubmissions" Member="PostSubmissions">
    <Type Name="PostSubmission">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Size" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FilePath" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PostId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Post_PostSubmission" Member="Post" ThisKey="PostId" OtherKey="Id" Type="Post" IsForeignKey="true" />
      <Association Name="User_PostSubmission" Member="User" ThisKey="UserID" OtherKey="Id" Type="User" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Resource" Member="Resources">
    <Type Name="Resource">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ClassId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Tag" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Path" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="UserClass_Resource" Member="UserClass" ThisKey="ClassId" OtherKey="Id" Type="UserClass" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Message" Member="Messages">
    <Type Name="Message">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Message" Member="Message1" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
</Database>